# Numpy exercises

HINT: use the Numpy documentations
* [NumPy User Guide](https://numpy.org/doc/1.22/user/index.html#user)
* [NumPy API](https://numpy.org/doc/1.22/reference/index.html#reference)

In [3]:
import numpy as np

#### 1) Create a null vector of size 10 (★☆☆)

In [7]:
# Var 1
np.array([None]*10)

array([None, None, None, None, None, None, None, None, None, None],
      dtype=object)

In [11]:
# Var 2
np.array([np.NaN]*10)

array([nan, nan, nan, nan, nan, nan, nan, nan, nan, nan])

In [17]:
# Var 3
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### 2) Print the memory size in bytes of any array (★☆☆)

In [15]:
Z = np.zeros((10,10))
print(Z.size)
print(Z.itemsize)
print("In Byte: ", Z.size*Z.itemsize)
print("Elements: ", Z.size/Z.itemsize)

100
8
In Byte:  800
Elements:  12.5


#### 3) Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [18]:
Z = np.zeros(10)
print(Z)
Z[4] = 5
Z

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


array([0., 0., 0., 0., 5., 0., 0., 0., 0., 0.])

#### 4) Create a vector with values ranging from 10 to 49 (★☆☆)

In [19]:
np.arange(10, 50)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

#### 5) Reverse a vector (first element becomes last) (★☆☆)

In [21]:
np.arange(50)[-1:0:-1]


array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

#### 6) Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [22]:
np.arange(9).reshape((3, 3))

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### 7) Find indices of non-zero elements from \[1,2,0,0,4,0\] (★☆☆)

In [27]:
arr = np.array([1,2,0,0,4,0])
np.where(arr != 0)

(array([0, 1, 4]),)

#### 8) Create a 3x3 identity matrix (★☆☆)

In [28]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### 9) Create a 3x3x3 array with random values (★☆☆)

In [33]:
np.random.rand(9*3).reshape((3, 3, -1))

array([[[0.923459  , 0.18600353, 0.10590417],
        [0.7231698 , 0.2615831 , 0.28050049],
        [0.39675651, 0.41579603, 0.53670731]],

       [[0.31960518, 0.12464403, 0.26362221],
        [0.15848953, 0.39850787, 0.29753768],
        [0.27230983, 0.93008265, 0.78489017]],

       [[0.9301852 , 0.49827221, 0.81107824],
        [0.46685227, 0.92230931, 0.06029591],
        [0.06670089, 0.31736092, 0.61467239]]])

#### 10) Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [39]:
arr = np.random.rand(10*10).reshape(10, -1)
print("min:",round(arr.min(), 2), " max:", round(arr.max(), 2))

min: 0.02  max: 1.0


#### 11) Create a random vector of size 30 and find the mean value (★☆☆)

In [40]:
np.random.rand(30).mean()

0.47952129582077613

#### 12) Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [45]:
Z = np.zeros((9,9))
Z = np.pad(Z, pad_width=1, mode='constant', constant_values=1)
Z

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

#### 13) How to add a border (filled with 0's) around an existing array? (★☆☆)

In [44]:
Z = np.ones((5,5))
np.pad(Z, pad_width=1, mode="constant", constant_values=0)

array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])

#### 14) Predict (before executig) the results of the following expressions? (★☆☆)

In [46]:
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(np.nan in set([np.nan]))
print(0.3 == 3 * 0.1)

# My guess
# 0
# True
# False
# np.nan
# True
# False

nan
False
False
nan
True
False


#### 15) Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [55]:
arr = np.zeros(5*5).reshape((5, -1))
np.fill_diagonal(arr, np.arange(1, 5)) 
arr

array([[1., 0., 0., 0., 0.],
       [0., 2., 0., 0., 0.],
       [0., 0., 3., 0., 0.],
       [0., 0., 0., 4., 0.],
       [0., 0., 0., 0., 1.]])

#### 16) Create a 8x8 matrix and fill it with a checkerboard (0,1) pattern (★☆☆)

In [ ]:
Z = np.zeros((8,8),dtype=int)


#### 17) Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

#### 18) Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

#### 19) Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [ ]:
# Author: Evgeni Burovski

Z = np.arange(11)


#### 20. How to find common values between two arrays? (★☆☆)

In [ ]:
Z1 = np.random.randint(0,10,10)
Z2 = np.random.randint(0,10,10)


#### 21) How to compute ((A+B)\*(-A/2)) in place (without copy)? (★★☆)

In [ ]:
A = np.ones(3)*1
B = np.ones(3)*2
C = np.ones(3)*3


#### 22) Extract the integer part of a random array (★★☆)

In [ ]:
Z = np.random.uniform(0,10,10)



#### 23) Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [ ]:
Z = np.zeros((5,5))


#### 24) Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

#### 25) Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

#### 26) Create a random vector of size 10 and sort it (★★☆)

#### 27) Consider two random array A and B, check if they are equal (★★☆)

In [ ]:
A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)



#### 28) Make an array immutable (read-only) (★★☆)

In [ ]:
Z = np.zeros(10)


#### 29) Create random vector of size 10 and replace the maximum value by 0 (★★☆)

In [ ]:
Z = np.random.random(10)


#### 30) How to convert a float (32 bits) array into an integer (32 bits) in place?

In [ ]:
Z = np.arange(10, dtype=np.float32)


#### 31) randomly place 3 elements in a 2D array? (★★☆)

In [ ]:

n = 10
p = 3
Z = np.zeros((n,n))


#### 32) Subtract the mean of each row of a matrix (★★☆)

In [ ]:
X = np.random.rand(5, 10)


#### 33) sort an array by the 1st column? (★★☆)

In [ ]:
Z = np.random.randint(0,10,(3,3))
Z

array([[2, 8, 3],
       [3, 0, 4],
       [3, 3, 7]])

#### 34) Find the nearest value from a given value z  in an array Z(★★☆)

In [ ]:
Z = np.random.uniform(0,1,10)
z = 0.5


#### 35) Considering two arrays with shape (1,3) and (3,1): to compute their sum using an iterator (★★☆)

In [ ]:
A = np.arange(3).reshape(3,1)
B = np.arange(3).reshape(1,3)


#### 36) find the most frequent value in an array

In [ ]:
Z = np.random.randint(0,10,50)


#### 37) Given a two dimensional array, extract unique rows (★★★)

In [ ]:

Z = np.random.randint(0,2,(6,3))
