# Recalling Numpy Array Slicing and Indexing

In [1]:
import numpy as np

In [59]:
#create array
x = np.asarray(range(1,26), np.int8).reshape(5,5)

In [3]:
x

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]], dtype=int8)

## Slice first 3 elements

<img src="https://github.com/xXAI-botXx/DataEngineering22/blob/main/week_1/IMG/np01.png?raw=1">

In [10]:
x[0,0:3]


array([1, 2, 3], dtype=int8)

##  Slice first 8 elements

<img src="https://github.com/xXAI-botXx/DataEngineering22/blob/main/week_1/IMG/np02.png?raw=1">

In [74]:
x.reshape((1, -1))[0, 0:8]

array([1, 2, 3, 4, 5, 6, 7, 8], dtype=int8)

In [77]:
x.flatten()[0:8]

array([1, 2, 3, 4, 5, 6, 7, 8], dtype=int8)

## Skip every other element

<img src="https://github.com/xXAI-botXx/DataEngineering22/blob/main/week_1/IMG/np03.png?raw=1">

In [21]:
x[0, ::2]

array([1, 3, 5], dtype=int8)

## Slice first column

<img src="https://github.com/xXAI-botXx/DataEngineering22/blob/main/week_1/IMG/np04.png?raw=1">

In [22]:
x[0:4, 0]

array([ 1,  6, 11, 16], dtype=int8)

## Slice a diagonal

<img src="https://github.com/xXAI-botXx/DataEngineering22/blob/main/week_1/IMG/np05.png?raw=1">

In [61]:
np.diagonal(x, 0)

array([ 1,  7, 13, 19, 25], dtype=int8)

## Repeat the first element

<img src="https://github.com/xXAI-botXx/DataEngineering22/blob/main/week_1/IMG/np06.png?raw=1">

In [29]:
np.repeat(x[0, 0], x.shape[1])

array([1, 1, 1, 1, 1], dtype=int8)

In [80]:
np.tile(x[0, 0], (1,5))[0]

array([1, 1, 1, 1, 1], dtype=int8)

In [82]:
np.broadcast(x[0, 0], (1, 5)) # FIXME

## Simple 2D slicing

<img src="https://github.com/xXAI-botXx/DataEngineering22/blob/main/week_1/IMG/np07.png?raw=1">

In [30]:
x[0:3, 0:4]

array([[ 1,  2,  3,  4],
       [ 6,  7,  8,  9],
       [11, 12, 13, 14]], dtype=int8)

## Slice a zigzag 

<img src="https://github.com/xXAI-botXx/DataEngineering22/blob/main/week_1/IMG/np08.png?raw=1">

In [70]:
np.append(np.diagonal(x, 0)[0:4], np.diagonal(x, 1)).reshape((-1, 2))
# FIXME


array([[ 1,  7],
       [13, 19],
       [ 2,  8],
       [14, 20]], dtype=int8)

In [96]:
np.append(x.flatten()[::6][0:-1], x.flatten()[1::6]).reshape((-1, 2))

SyntaxError: ignored

## Sparse slicing

<img src="https://github.com/xXAI-botXx/DataEngineering22/blob/main/week_1/IMG/np09.png?raw=1">

In [37]:
x[0::2, 0::2]

array([[ 1,  3,  5],
       [11, 13, 15],
       [21, 23, 25]], dtype=int8)

## Transpose a 2D array

<img src="https://github.com/xXAI-botXx/DataEngineering22/blob/main/week_1/IMG/np10.png?raw=1">

In [38]:
np.transpose(x[0:3, 0:3])

array([[ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13]], dtype=int8)

## Repeat the first column 4 times


<img src="https://github.com/xXAI-botXx/DataEngineering22/blob/main/week_1/IMG/np11.png?raw=1">

In [40]:
np.repeat(x[:,0], 4).reshape((5, -1))

array([[ 1,  1,  1,  1],
       [ 6,  6,  6,  6],
       [11, 11, 11, 11],
       [16, 16, 16, 16],
       [21, 21, 21, 21]], dtype=int8)

In [42]:
np.transpose([x[:, 0]]*4)

array([[ 1,  1,  1,  1],
       [ 6,  6,  6,  6],
       [11, 11, 11, 11],
       [16, 16, 16, 16],
       [21, 21, 21, 21]], dtype=int8)

In [ ]:
# broadcast FIXME

## Reshape 1D array to 2D array

<img src="https://github.com/xXAI-botXx/DataEngineering22/blob/main/week_1/IMG/np12.png?raw=1">

In [48]:
x = np.asarray(range(1,13), np.int64)
print(x)


[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [49]:
x.reshape(-1, 3)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

## Collapse an axis from a 3D array

<img src="https://github.com/xXAI-botXx/DataEngineering22/blob/main/week_1/IMG/np13.png?raw=1">

In [51]:
x = np.asarray(range(1,13), np.int8).reshape(3,2,2)
print(x)

[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]]


In [54]:
x.shape

(3, 2, 2)

In [56]:
x.reshape((3, -1))

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]], dtype=int8)